name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-techdocs.yaml'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@46f48da11e78ebdba7a8747ae456b11062fac83e # main
    with:
      namespace: default
      kind: component
      name: alloy-configurator
      default-working-directory: .
