name: Publish TechDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'catalog-info.yaml'
      - '.github/workflows/publish-techdocs.yaml'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  publish-docs:
    uses: grafana/shared-workflows/.github/workflows/publish-techdocs.yaml@8eef102d2f5f93bc3d2b26937e7bec29115d81e8 # main
    with:
      namespace: default
      kind: component
      name: alloy-configurator
      default-working-directory: .
